[project]
name = "zbToolLib"
version = "2.0.5"
description = "zb工具库"
requires-python = ">=3.12"
dependencies = [
    "send2trash>=1.8.3",
    "requests>=2.32.5",
    "winshell>=0.6; sys_platform == 'win32'",
    "pywin32>=311; sys_platform == 'win32'",
    "puremagic>=1.30",
]
authors = [
    { name = "Ianzb", email = "93322252@qq.com" },
]
maintainers = [
    { name = "Ianzb", email = "93322252@qq.com" },
]
readme = "README.md"
license = { text = "MIT License" }
keywords = ["zb", "Ianzb", "tool", "lib"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Repository = "https://github.com/Ianzb/zbToolLib/"