name: 上传 Python 包

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "zbToolLib/**"
  pull_request:
    branches: [ main ]
    paths:
      - "zbToolLib/**"

permissions:
  contents: write
  id-token: write

jobs:
  release-build:
    name: 构建发行包
    runs-on: windows-latest
    outputs:
      package: ${{ steps.meta.outputs.package }}
      version: ${{ steps.meta.outputs.version }}

    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 设置 Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: 安装 uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: 安装项目
        run: uv sync --no-group dev

      - name: 构建分发包
        run: |
          uv build --no-sources

      - name: 上传构建产物
        uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/